In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

In [2]:
priceData = pd.read_csv('all_stocks_5yr.csv')

In [3]:
processed = pd.DataFrame()
for stock in np.unique(priceData["Name"]):
    df = pd.DataFrame()
    df = priceData.loc[priceData['Name'] == stock][['date','close']]
    df = df.transpose()
    df.columns = df.iloc[0]
    df = df.drop(df.index[0])
    df = df.rename(index={'close': stock})
    processed = pd.concat([processed, df])
processed

date,2013-02-08,2013-02-11,2013-02-12,2013-02-13,2013-02-14,2013-02-15,2013-02-19,2013-02-20,2013-02-21,2013-02-22,...,2018-01-25,2018-01-26,2018-01-29,2018-01-30,2018-01-31,2018-02-01,2018-02-02,2018-02-05,2018-02-06,2018-02-07
A,45.08,44.6,44.62,44.75,44.58,42.25,43.01,42.24,41.63,41.8,...,73.86,74.82,74.53,72.99,73.43,72.83,71.25,68.22,68.45,68.06
AAL,14.75,14.46,14.27,14.66,13.99,14.5,14.26,13.33,13.37,13.57,...,53.05,53.07,52.68,52.59,54.32,53.88,52.1,49.76,51.18,51.4
AAP,78.9,78.39,78.6,78.97,78.84,79,80.72,79.5,79.06,79.21,...,120.92,123.64,122.89,119.27,116.99,117.29,113.93,109.86,112.2,109.93
AAPL,67.8542,68.5614,66.8428,66.7156,66.6556,65.7371,65.7128,64.1214,63.7228,64.4014,...,171.11,171.51,167.96,166.97,167.43,167.78,160.5,156.49,163.03,159.54
ABBV,36.25,35.85,35.42,35.27,36.57,37.58,38.19,38.61,38.78,38.46,...,108.3,123.21,122.31,115.88,112.22,116.34,115.17,109.51,111.2,113.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XYL,27.09,27.46,27.95,28.26,28.47,28.28,28.76,27.96,27.68,27.79,...,73.24,74.41,73.41,73.07,72.26,74.84,75.66,72.66,71.33,71.79
YUM,65.3,64.55,64.75,64.41,63.89,63.99,65.15,64.56,65.05,65.45,...,85.66,86.2,86.48,84.59,84.59,83.98,82.63,79.8,80.58,80.13
ZBH,75.85,75.65,75.44,76,76.34,75.9,76.11,75.31,73.87,74.14,...,124.74,126.23,127.39,125.94,127.12,128.19,125.79,123.18,122.3,120.78
ZION,24.14,24.21,24.49,24.74,24.63,24.34,24.69,24.14,23.73,24.04,...,53.02,54.02,54.19,53.93,54.03,54.98,54.15,51.65,52.52,54.02
ZTS,33.05,33.26,33.74,33.55,33.27,33.98,33.84,32.72,32.56,32.59,...,79.25,80.09,79.18,78.35,76.73,77.82,76.78,73.83,73.27,73.86

In [4]:
dailyChange = processed.T.pct_change().T #calculate daily percent change
dailyChange = dailyChange.drop(['2013-02-08'], axis = 1) #needed because first column will be null due to percent change
dailyChange = dailyChange.dropna() #drop stocks that do not start at date: 2013-02-08
dailyChange.head()

date,2013-02-11,2013-02-12,2013-02-13,2013-02-14,2013-02-15,2013-02-19,2013-02-20,2013-02-21,2013-02-22,2013-02-25,...,2018-01-25,2018-01-26,2018-01-29,2018-01-30,2018-01-31,2018-02-01,2018-02-02,2018-02-05,2018-02-06,2018-02-07
A,-0.010648,0.000448,0.002913,-0.003799,-0.052266,0.017988,-0.017903,-0.014441,0.004084,-0.012201,...,0.003805,0.012998,-0.003876,-0.020663,0.006028,-0.008171,-0.021694,-0.042526,0.003371,-0.005698
AAL,-0.019661,-0.013140,0.027330,-0.045703,0.036455,-0.016552,-0.065217,0.003001,0.014959,-0.040531,...,-0.031758,0.000377,-0.007349,-0.001708,0.032896,-0.008100,-0.033036,-0.044914,0.028537,0.004299
AAP,-0.006464,0.002679,0.004707,-0.001646,0.002029,0.021772,-0.015114,-0.005535,0.001897,-0.010731,...,-0.000579,0.022494,-0.006066,-0.029457,-0.019116,0.002564,-0.028647,-0.035724,0.021300,-0.020232
AAPL,0.010422,-0.025067,-0.001903,-0.000899,-0.013780,-0.000370,-0.024218,-0.006216,0.010649,-0.017768,...,-0.017851,0.002338,-0.020699,-0.005894,0.002755,0.002090,-0.043390,-0.024984,0.041792,-0.021407
ABBV,-0.011034,-0.011994,-0.004235,0.036859,0.027618,0.016232,0.010998,0.004403,-0.008252,-0.028341,...,0.026443,0.137673,-0.007305,-0.052571,-0.031584,0.036714,-0.010057,-0.049145,0.015432,0.021763

In [5]:
pca_model = PCA(n_components = 100)
pca_model.fit(dailyChange.T)
pca_model.components_.T.shape

(476, 100)

In [6]:
dimReduced = pd.DataFrame(data = pca_model.components_.T, index = dailyChange.index)
dimReduced = dimReduced.add_prefix("P")
dimReduced.head()

,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,P90,P91,P92,P93,P94,P95,P96,P97,P98,P99
A,-0.052106,-0.016433,0.016918,-0.039732,0.005226,0.010964,0.027430,-0.008232,0.024945,-0.014859,...,-0.058235,0.039439,0.036417,-0.034094,-0.168639,-0.100671,0.052851,-0.048336,0.106436,-0.008475
AAL,-0.061322,-0.056385,0.066372,-0.005943,-0.025348,-0.082604,-0.081009,-0.187887,-0.238921,-0.017283,...,-0.023705,-0.002193,-0.073359,0.034722,-0.003021,0.006366,-0.066756,0.082677,-0.050510,0.045164
AAP,-0.040687,-0.022934,-0.004541,0.085318,-0.076210,-0.025629,0.028174,0.019683,-0.008663,0.006429,...,0.078544,-0.002671,-0.027248,0.060757,0.029011,-0.129824,-0.066347,-0.005319,-0.022641,0.013890
AAPL,-0.035636,-0.017763,0.010961,-0.046832,0.033142,-0.035528,0.042772,-0.002989,-0.004477,-0.017919,...,-0.030979,0.025433,0.052466,-0.051968,0.067323,0.007682,-0.011683,-0.072149,0.012155,0.032636
ABBV,-0.044225,-0.031625,-0.002505,-0.052149,-0.076562,0.068573,-0.014589,0.013692,0.023303,0.008426,...,0.084112,0.063105,0.007344,0.117597,-0.029544,0.050300,-0.063861,-0.053109,-0.032319,-0.061275